name: deploy-prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Build & Export
        run: |
          yarn install
          yarn build

      - name: Deploy to S3 and Invalidate Cloudfront
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
        run: |
          aws s3 sync ./dist s3://waffle2024-prod --delete
          aws cloudfront create-invalidation --distribution-id E298REBL12VEW6 --paths "/*"
